Sticks and Exclusive Recipes
RockBottomGame/API pull request #35
Opened 2019-08-13 11:42 UTC by raphydaphy

2019-08-13 11:56 UTC, Quarris requested changes

2019-08-13 11:56 UTC, Quarris commented on src/main/java/de/ellpeck/rockbottom/api/construction/compendium/construction/ConstructionRecipe.java
> +    protected final boolean constructionTable;
I would change this to be "manual" or "manualOnly" and then change the "showInConstructionTable" to be "!manual"

2019-08-13 11:56 UTC, Quarris commented on src/main/java/de/ellpeck/rockbottom/api/construction/compendium/construction/ConstructionRecipe.java
> +        return constructionTable;
also... "this."

2019-08-13 12:26 UTC, Quarris approved these changes

2019-08-13 12:27 UTC, Quarris approved these changes

2019-08-14 05:11 UTC, canitzp approved these changes

2019-08-14 07:26 UTC, merged