Smithing
RockBottomGame/API pull request #36
Opened 2019-08-14 15:28 UTC by Quarris

2019-08-14 19:15 UTC, canitzp commented on src/main/java/de/ellpeck/rockbottom/api/IApiHandler.java
> +	 * @param actualInputs    The actual {@link ItemInstance}s used in the construction of the recipe.
tab instead of spaces

2019-08-14 19:15 UTC, canitzp commented on src/main/java/de/ellpeck/rockbottom/api/IApiHandler.java
> +	 * @see IApiHandler#defaultConstruct(AbstractEntityPlayer, PlayerCompendiumRecipe, TileEntity)
tab instead of spaces

2019-08-14 19:15 UTC, canitzp commented on src/main/java/de/ellpeck/rockbottom/api/Registries.java
> +	/**
tab instead of spaces

2019-08-14 19:17 UTC, canitzp requested changes
Even if you aren't seeing the formatting errors, other can see it. Tab intendation should be spaces. IntelliJ should be set to spaces automaticly

2019-08-14 19:52 UTC, Quarris commented
I changed the settings to spaces (and also put else on same line since I always have it on new line) and reformatted the files. So decent amount of changes :P

2019-08-15 05:19 UTC, canitzp approved these changes

2019-08-15 08:03 UTC, raphydaphy approved these changes

2019-08-15 08:46 UTC, merged